name: CD - Helm Deploy Microservices

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/cd-helm.yml'
  workflow_dispatch:

jobs:
  deploy-microservices:
    runs-on: self-hosted
    steps:
      # ======================
      # Checkout Infra Repo
      # ======================
      - name: Checkout infra repo
        uses: actions/checkout@v4

      # ======================
      # Setup Kubernetes context
      # ======================
      - name: Setup kubectl
        run: |
          echo "Setting up Kubernetes context"
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          kubectl get nodes

      # ======================
      # Deploy Microservices via Helm
      # ======================
      - name: Deploy all microservices
        run: |
          MICROSERVICES=("user-auth-service" "data-upload-service" "analytics-service" "frontend-service")
          NAMESPACE="analytics"
          for svc in "${MICROSERVICES[@]}"; do
            echo "=== Deploying $svc ==="
            
            # Create namespace if it doesn't exist
            if ! kubectl get namespace $NAMESPACE >/dev/null 2>
