name: Setup Infra and Deploy GitHub Runner

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Get short-lived runner token
        id: get_token
        shell: bash
        run: |
          TOKEN=$(curl -sX POST \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/SUBANALYTICS/actions/runners/registration-token \
            | jq -r .token)
          echo "RUNNER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: Terraform   # Matches your repo folder
        run: terraform init

      - name: Terraform Apply
        working-directory: Terraform   # Matches your repo folder
        run: terraform apply -auto-approve
        env:
          TF_VAR_runner_token: ${{ env.RUNNER_TOKEN }}

